"use client";
import { useState } from "react";
import TopBar from "@/components/layout/TopBar";
import { projects, monthlyGeneration, getProjectStats, getPortfolioSummary } from "@/lib/data";
import { formatMWh, formatNPR, getPLFColor, cn } from "@/lib/utils";
import { FileText, Download, Calendar, Filter, BarChart3, DollarSign, Zap, Droplets } from "lucide-react";
import * as XLSX from "xlsx";

type ReportType = "monthly" | "annual" | "portfolio";

export default function ReportsPage() {
  const [reportType, setReportType] = useState<ReportType>("monthly");
  const [selectedProject, setSelectedProject] = useState("p1");
  const [selectedMonth, setSelectedMonth] = useState("3"); // March
  const [selectedYear, setSelectedYear] = useState("2026");

  const months = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ];

  // Get data for selected report
  const monthlyData = monthlyGeneration.filter(r =>
    r.projectId === selectedProject &&
    r.month === parseInt(selectedMonth) &&
    r.year === parseInt(selectedYear)
  )[0];

  const annualData = monthlyGeneration.filter(r =>
    r.projectId === selectedProject && r.year === parseInt(selectedYear)
  );

  const portfolio = getPortfolioSummary();
  const proj = projects.find(p => p.id === selectedProject)!;

  function exportExcel() {
    let rows: (string | number)[][];
    let filename = "";

    if (reportType === "monthly" && monthlyData) {
      const isWet = monthlyData.isWetSeason;
      const tariff = isWet ? proj.neaTariff.wet : proj.neaTariff.dry;
      rows = [
        ["HydroTrack Nepal — Monthly Generation Report"],
        [""],
        ["Project", proj.name],
        ["Location", proj.location],
        ["River", proj.river],
        ["Period", `${months[monthlyData.month - 1]} ${monthlyData.year}`],
        ["Season", isWet ? "Wet" : "Dry"],
        [""],
        ["GENERATION SUMMARY", ""],
        ["Planned Generation (MWh)", monthlyData.plannedGeneration],
        ["Actual Generation (MWh)", monthlyData.actualGeneration],
        ["Achievement (%)", `${((monthlyData.actualGeneration / monthlyData.plannedGeneration) * 100).toFixed(1)}%`],
        ["Plant Load Factor (%)", `${monthlyData.plf}%`],
        ["Grid Availability (%)", `${monthlyData.gridAvailability}%`],
        ["Spill Hours", monthlyData.spillHours],
        [""],
        ["REVENUE", ""],
        ["NEA Tariff (NPR/kWh)", tariff],
        ["Total Revenue (NPR)", monthlyData.revenue],
        ["Total Revenue (NPR M)", `${(monthlyData.revenue / 1_000_000).toFixed(2)}M`],
        [""],
        ["PLANT SPECIFICATIONS", ""],
        ["Installed Capacity (MW)", proj.installedCapacity],
        ["Design Flow (m³/s)", proj.designFlow],
        ["Net Head (m)", proj.headHeight],
        ["Number of Turbines", proj.turbines],
        [""],
        ["Report generated by HydroTrack Nepal", new Date().toLocaleDateString()],
      ];
      filename = `${proj.name}_${months[monthlyData.month - 1]}_${monthlyData.year}_Report.xlsx`;
    } else if (reportType === "annual") {
      rows = [
        ["HydroTrack Nepal — Annual Generation Report"],
        [""],
        ["Project", proj.name],
        ["Year", selectedYear],
        [""],
        ["Month", "Planned (MWh)", "Actual (MWh)", "PLF (%)", "Grid Avail. (%)", "Spill Hrs", "Revenue (NPR)"],
        ...annualData.map(r => [
          months[r.month - 1], r.plannedGeneration, r.actualGeneration,
          r.plf, r.gridAvailability, r.spillHours, r.revenue
        ]),
        [""],
        ["TOTALS", ""],
        ["Total Planned (MWh)", annualData.reduce((s, r) => s + r.plannedGeneration, 0)],
        ["Total Actual (MWh)", annualData.reduce((s, r) => s + r.actualGeneration, 0)],
        ["Total Revenue (NPR)", annualData.reduce((s, r) => s + r.revenue, 0)],
        ["Avg PLF (%)", (annualData.reduce((s, r) => s + r.plf, 0) / annualData.length).toFixed(1)],
        [""],
        ["Report generated by HydroTrack Nepal", new Date().toLocaleDateString()],
      ];
      filename = `${proj.name}_${selectedYear}_Annual_Report.xlsx`;
    } else {
      rows = [
        ["HydroTrack Nepal — Portfolio Summary Report"],
        [""],
        ["Total Installed Capacity (MW)", projects.reduce((s, p) => s + p.installedCapacity, 0)],
        ["Active Projects", projects.filter(p => p.status === "operational").length],
        [""],
        ["PROJECT", "CAPACITY (MW)", "STATUS", "GEN YTD (MWh)", "REVENUE YTD (NPR)", "AVG PLF (%)"],
        ...projects.map(p => {
          const stats = getProjectStats(p.id);
          return [p.name, p.installedCapacity, p.status, stats.totalGenYTD, stats.totalRevYTD, stats.avgPLF.toFixed(1)];
        }),
        [""],
        ["Report generated by HydroTrack Nepal", new Date().toLocaleDateString()],
      ];
      filename = `HydroTrack_Portfolio_${selectedYear}_Report.xlsx`;
    }

    const ws = XLSX.utils.aoa_to_sheet(rows);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Report");
    XLSX.writeFile(wb, filename);
  }

  return (
    <div className="min-h-screen">
      <TopBar title="Reports" />
      <div className="p-4 lg:p-6 space-y-5 animate-fade-in max-w-5xl">

        {/* Report type tabs */}
        <div className="flex bg-[#0f1929] border border-[#1e3a5f] rounded-xl overflow-hidden w-fit">
          {(["monthly", "annual", "portfolio"] as ReportType[]).map(t => (
            <button
              key={t}
              onClick={() => setReportType(t)}
              className={cn(
                "px-5 py-2.5 text-sm font-medium capitalize transition-colors",
                reportType === t
                  ? "bg-blue-500/15 text-blue-400"
                  : "text-gray-400 hover:text-white"
              )}
            >
              {t === "portfolio" ? "Portfolio" : t.charAt(0).toUpperCase() + t.slice(1)}
            </button>
          ))}
        </div>

        {/* Filters */}
        <div className="flex flex-wrap gap-3 items-center bg-[#0f1929] border border-[#1e3a5f] rounded-xl p-4">
          <Filter className="w-4 h-4 text-gray-500" />
          {reportType !== "portfolio" && (
            <select
              value={selectedProject}
              onChange={e => setSelectedProject(e.target.value)}
              className="bg-[#162035] border border-[#1e3a5f] text-sm text-white rounded-lg px-3 py-1.5 outline-none"
            >
              {projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
            </select>
          )}
          {reportType === "monthly" && (
            <select
              value={selectedMonth}
              onChange={e => setSelectedMonth(e.target.value)}
              className="bg-[#162035] border border-[#1e3a5f] text-sm text-white rounded-lg px-3 py-1.5 outline-none"
            >
              {months.map((m, i) => <option key={i} value={i + 1}>{m}</option>)}
            </select>
          )}
          <select
            value={selectedYear}
            onChange={e => setSelectedYear(e.target.value)}
            className="bg-[#162035] border border-[#1e3a5f] text-sm text-white rounded-lg px-3 py-1.5 outline-none"
          >
            <option value="2026">2026</option>
            <option value="2025">2025</option>
          </select>
          <button
            onClick={exportExcel}
            className="ml-auto btn-primary text-sm font-medium px-4 py-2 rounded-xl text-white flex items-center gap-2"
          >
            <Download className="w-4 h-4" />
            Export Excel
          </button>
        </div>

        {/* Monthly Report Preview */}
        {reportType === "monthly" && monthlyData && (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h2 className="font-semibold text-white">
                {months[monthlyData.month - 1]} {monthlyData.year} — {proj.name}
              </h2>
              <span className={cn("text-xs px-2 py-1 rounded-full",
                monthlyData.isWetSeason ? "text-blue-400 bg-blue-500/10" : "text-amber-400 bg-amber-500/10"
              )}>
                {monthlyData.isWetSeason ? "Wet Season" : "Dry Season"}
              </span>
            </div>

            <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
              {[
                { label: "Actual Generation", value: formatMWh(monthlyData.actualGeneration), icon: Zap, color: "text-blue-400 bg-blue-500/10" },
                { label: "Plant Load Factor", value: `${monthlyData.plf}%`, icon: BarChart3, color: `${getPLFColor(monthlyData.plf)} bg-purple-500/10` },
                { label: "Grid Availability", value: `${monthlyData.gridAvailability}%`, icon: Droplets, color: "text-cyan-400 bg-cyan-500/10" },
                { label: "Revenue", value: formatNPR(monthlyData.revenue), icon: DollarSign, color: "text-green-400 bg-green-500/10" },
              ].map(kpi => (
                <div key={kpi.label} className="bg-[#0f1929] border border-[#1e3a5f] rounded-xl p-4">
                  <div className={`w-8 h-8 rounded-lg flex items-center justify-center mb-2 ${kpi.color}`}>
                    <kpi.icon className="w-4 h-4" />
                  </div>
                  <p className="text-lg font-bold text-white">{kpi.value}</p>
                  <p className="text-xs text-gray-500 mt-0.5">{kpi.label}</p>
                </div>
              ))}
            </div>

            <div className="bg-[#0f1929] border border-[#1e3a5f] rounded-xl overflow-hidden">
              <div className="px-5 py-4 border-b border-[#1e3a5f]">
                <h3 className="font-medium text-white text-sm">Generation Details</h3>
              </div>
              <div className="p-5 grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
                {[
                  ["Project", proj.name],
                  ["Location", proj.location],
                  ["River", proj.river],
                  ["Period", `${months[monthlyData.month - 1]} ${monthlyData.year}`],
                  ["Planned Generation", formatMWh(monthlyData.plannedGeneration)],
                  ["Actual Generation", formatMWh(monthlyData.actualGeneration)],
                  ["Achievement", `${((monthlyData.actualGeneration / monthlyData.plannedGeneration) * 100).toFixed(1)}%`],
                  ["Spill Hours", `${monthlyData.spillHours} hrs`],
                  ["NEA Tariff", `NPR ${monthlyData.isWetSeason ? proj.neaTariff.wet : proj.neaTariff.dry}/kWh`],
                  ["Revenue", formatNPR(monthlyData.revenue)],
                  ["Installed Capacity", `${proj.installedCapacity} MW`],
                  ["Operator", proj.operator],
                ].map(([k, v]) => (
                  <div key={k} className="flex justify-between border-b border-[#1e3a5f]/50 pb-2">
                    <span className="text-gray-500">{k}</span>
                    <span className="text-white font-medium">{v}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Annual Report Preview */}
        {reportType === "annual" && (
          <div className="space-y-4">
            <h2 className="font-semibold text-white">{selectedYear} Annual Report — {proj.name}</h2>
            <div className="bg-[#0f1929] border border-[#1e3a5f] rounded-2xl overflow-hidden">
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-[#1e3a5f]">
                      {["Month", "Season", "Planned (GWh)", "Actual (GWh)", "PLF", "Grid Avail.", "Spill Hrs", "Revenue"].map(h => (
                        <th key={h} className="text-left text-xs text-gray-500 font-medium px-4 py-3 whitespace-nowrap">{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {annualData.map((r, i) => (
                      <tr key={r.id} className={cn("border-b border-[#1e3a5f]/50 hover:bg-[#162035]",
                        i % 2 === 0 ? "" : "bg-[#0f1929]/50")}>
                        <td className="px-4 py-3 text-gray-300 font-medium">{r.monthName}</td>
                        <td className="px-4 py-3">
                          <span className={cn("text-xs px-2 py-0.5 rounded-full",
                            r.isWetSeason ? "text-blue-400 bg-blue-500/10" : "text-amber-400 bg-amber-500/10"
                          )}>
                            {r.isWetSeason ? "Wet" : "Dry"}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-gray-400">{(r.plannedGeneration / 1000).toFixed(2)}</td>
                        <td className="px-4 py-3 text-white font-medium">{(r.actualGeneration / 1000).toFixed(2)}</td>
                        <td className="px-4 py-3">
                          <span className={cn("font-semibold", getPLFColor(r.plf))}>{r.plf.toFixed(1)}%</span>
                        </td>
                        <td className="px-4 py-3 text-gray-400">{r.gridAvailability.toFixed(1)}%</td>
                        <td className="px-4 py-3 text-gray-400">{r.spillHours}h</td>
                        <td className="px-4 py-3 text-green-400">{formatNPR(r.revenue)}</td>
                      </tr>
                    ))}
                  </tbody>
                  <tfoot>
                    <tr className="border-t-2 border-[#1e3a5f] bg-[#162035]">
                      <td colSpan={2} className="px-4 py-3 text-sm font-bold text-white">TOTAL / AVG</td>
                      <td className="px-4 py-3 text-gray-300 font-medium">
                        {(annualData.reduce((s, r) => s + r.plannedGeneration, 0) / 1000).toFixed(2)} GWh
                      </td>
                      <td className="px-4 py-3 text-white font-bold">
                        {(annualData.reduce((s, r) => s + r.actualGeneration, 0) / 1000).toFixed(2)} GWh
                      </td>
                      <td className="px-4 py-3">
                        <span className={cn("font-bold", getPLFColor(annualData.reduce((s, r) => s + r.plf, 0) / annualData.length))}>
                          {annualData.length ? (annualData.reduce((s, r) => s + r.plf, 0) / annualData.length).toFixed(1) : "—"}%
                        </span>
                      </td>
                      <td className="px-4 py-3 text-gray-300">
                        {annualData.length ? (annualData.reduce((s, r) => s + r.gridAvailability, 0) / annualData.length).toFixed(1) : "—"}%
                      </td>
                      <td className="px-4 py-3 text-gray-300">
                        {annualData.reduce((s, r) => s + r.spillHours, 0)}h
                      </td>
                      <td className="px-4 py-3 text-green-400 font-bold">
                        {formatNPR(annualData.reduce((s, r) => s + r.revenue, 0))}
                      </td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          </div>
        )}

        {/* Portfolio Report Preview */}
        {reportType === "portfolio" && (
          <div className="space-y-4">
            <h2 className="font-semibold text-white">Portfolio Summary — {selectedYear} YTD</h2>
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
              {[
                { label: "Total Capacity", value: `${portfolio.totalCapacity.toFixed(1)} MW` },
                { label: "Total Generation YTD", value: formatMWh(portfolio.totalGenYTD) },
                { label: "Total Revenue YTD", value: formatNPR(portfolio.totalRevYTD) },
                { label: "Portfolio Avg PLF", value: `${portfolio.avgPLF.toFixed(1)}%` },
              ].map(kpi => (
                <div key={kpi.label} className="bg-[#0f1929] border border-[#1e3a5f] rounded-xl p-4 text-center">
                  <p className="text-xl font-bold gradient-text">{kpi.value}</p>
                  <p className="text-xs text-gray-500 mt-1">{kpi.label}</p>
                </div>
              ))}
            </div>
            <div className="bg-[#0f1929] border border-[#1e3a5f] rounded-2xl overflow-hidden">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-[#1e3a5f]">
                    {["Project", "Capacity", "Status", "Generated YTD", "Revenue YTD", "Avg PLF"].map(h => (
                      <th key={h} className="text-left text-xs text-gray-500 font-medium px-4 py-3">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {projects.map(p => {
                    const s = getProjectStats(p.id);
                    return (
                      <tr key={p.id} className="border-b border-[#1e3a5f]/50 hover:bg-[#162035]">
                        <td className="px-4 py-3">
                          <div className="flex items-center gap-2">
                            <div className="w-2 h-2 rounded-full" style={{ background: p.color }} />
                            <span className="text-white font-medium text-xs">{p.name}</span>
                          </div>
                        </td>
                        <td className="px-4 py-3 text-gray-400">{p.installedCapacity} MW</td>
                        <td className="px-4 py-3">
                          <span className={cn("text-xs px-2 py-0.5 rounded-full",
                            p.status === "operational" ? "text-green-400 bg-green-500/10" : "text-amber-400 bg-amber-500/10"
                          )}>
                            {p.status === "operational" ? "Online" : "Maintenance"}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-white font-medium">{formatMWh(s.totalGenYTD)}</td>
                        <td className="px-4 py-3 text-green-400">{formatNPR(s.totalRevYTD)}</td>
                        <td className="px-4 py-3">
                          <span className={cn("font-bold", getPLFColor(s.avgPLF))}>{s.avgPLF.toFixed(1)}%</span>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
