package com.ptcompanion.domain.model

import java.time.Instant

/**
 * Generated by a trainer from the roster screen and consumed exactly once by a client
 * during sign-up. The [code] is the Firestore document id (short, human-typeable) so
 * lookup during redemption is a single doc read rather than a query, which keeps the
 * security rule for redemption simple: a client may read one invite doc by id and, if
 * unused, atomically claim it.
 */
data class InviteCode(
    val code: String,
    val trainerId: String,
    val clientDisplayName: String? = null,
    val createdAt: Instant = Instant.now(),
    val expiresAt: Instant? = null,
    val used: Boolean = false,
    val usedByClientUserId: String? = null,
    val usedAt: Instant? = null,
)
